version: '3'
services:
  mongodb:
    image: "mongo"
    ports:
     - "27017:27017"
  ##    
  backend:
    build: 
      context: ./backend/build
      dockerfile: Dockerfile
    restart: always
    environment:
     - MONGODB_PROD_URI=${MONGODB_URI}
     - MONGODB_LOCAL_URI=mongodb://mongo:27017/test
     - JWTSECRET=${JWTSECRET}
     - SESSION_SECRET=${SESSION_SECRET}
     - SENDGRID_API_KEY=${SENDGRID_API_KEY}
     - SENDGRID_EMAIL_ADDRESS=${SENDGRID_EMAIL_ADDRESS}
     - COMPANY_NAME=${COMPANY_NAME}
     - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
     - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
     - S3_BUCKET=${S3_BUCKET}
     - AWS_REGION=${AWS_REGION}
     - HOST=${HOST}
     - PORT=${PORT}    
    ports:
      - "5000:5000"
    command: /usr/app/node_modules/.bin/nodemon src/index.js
    volumes:
      - ./backend
    depends_on:
      - mongodb
  ##
  frontend:
    build: 
        context:./frontend/build
        dockerfile: Dockerfile
    command: npm start
    ports:
      - "3300:3000"   # map localhost 3300 to 3000 in docker
    volumes:
      - ./frontend/usr/src
    depends_on:
      - backend
  nginx:
    image: "nginx"
    container_name: nginx
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static_files:/var/www
    ports: 
     - 80:80
     - 443:443
    depends_on:
      - app